// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quiz.Ui
{
    static class Vsix
    {
        public const string Id = "ea0eead2-1392-4c13-bb81-6f6c5de8a936";
        public const string Name = "Quiz2";
        public const string Description = @"A multi-choice computer science quiz whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "GeekQuiz, geek, quiz, fun, trivia";
    }
}
