using System.Collections.Generic;

namespace Quiz.Questions.Mine
{
    public class QuestionsMine
    {
        public static IEnumerable<GatewayResponse> GetGatewayResponses()
        {

            //ddos?
            //
            //
            //
            //

            //iife?
            //
            //
            //
            //

            //which is not podcast
            //checkin
            //merge conflict
            //syntax
            //request for commit
            //herding code

            var gatewayResponses = new List<GatewayResponse>
            {
                Common.Get(Category.Geek, DifficultyLevel.Hard, "You are a genius?",
                    "true",
                    "false"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What was the initial name for Visual Studio?",
                    "Boston",
                    "Phoenix",
                    "Portland",
                    "Seattle",
                    "Timbuktu"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "What does cdn stand for?",
                    "content delivery network",
                    "content distribution network",
                    "cascading delivery network",
                    "cross domain network",
                    "caught doing nothing"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is a DAG?",
                    "Directed acyclic graph",
                    "distribution above ground",
                    "distribution across ground",
                    "distributed architecture groups",
                    "dogs are great"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "CSP is short for?",
                    "content security policy",
                    "cross site privacy",
                    "cascading style presentation",
                    "code security policy",
                    "caught stealing panties"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "AMPQ?",
                    "Rabbit",
                    "Cat",
                    "Dog",
                    "Horse",
                    "Chicken"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Rabbit ..?",
                    "M.Q.",
                    "P.I.",
                    "D.C.",
                    "M.A.",
                    "P.C."),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is Brainfuck?",
                    "A programming language",
                    "A term used by programmers to describe hard-to-fix bugs",
                    "Any code that can get into an infinite loop",
                    "Any bug that exists in a high level programming language's compiler",
                    "A word not to be repeated"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is the abbreviation GAC short for?",
                    "global assembly cache",
                    "general assembly cache",
                    "global action cache",
                    "general activity cache"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "What is css short for?",
                    "cascading style sheets",
                    "cross site scripting",
                    "cascading script sheets",
                    "cascading style scripts",
                    "captain silly ship"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is the abbreviation WSDL short for?",
                    "Web Services Description Language",
                    "Web Services Design Language",
                    "Web Services Description Log",
                    "Web Standards for Design Langauages"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is the abbreviation SVG short for?",
                    "Scalable Vector Graphics",
                    "Standard Variable Graphics",
                    "Scalar Vector Graphic",
                    "Scalable Vector Graphs"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Where does the word \"Redis\" derived from?",
                    "REmote DIctionary Server",
                    "REadable DIctionary Server",
                    "REduced DIctionary Server",
                    "REplicated DIctionary Server"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What does the acronym XSS mean?",
                    "cross site scripting",
                    "cross site sequel",
                    "excess server store",
                    "extinct server store",
                    "ex-secret service"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "What is the abbreviation SEO short for?",
                    "search engine optimization",
                    "senior executive officer",
                    "search engine organisation",
                    "senior executive order",
                    "small eggs omelette"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "What is meant by the acronym DRY?",
                    "don't repeat yourself",
                    "do repeat yourself",
                    "dynamic real-time yourdon principle",
                    "Dry run your code"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is XHR short for?",
                    "XML http object",
                    "cross http reader ",
                    "XML html object",
                    "cross html reader"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "The Xerox Corporation helped create Javascript?",
                    "true",
                    "false"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "What is an evergreen browser?",
                    "A browser that always runs the latest version of itself",
                    "Any browser with a green colour theme",
                    "A collective description for bug-free browsers",
                    "A browser that doesn't shed its leaves in the winter"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "The Microsoft SQL Server in-memory database for OLTP workloads is also known as?",
                    "Hekaton",
                    "Hackathon",
                    "Megatron",
                    "Segatron",
                    "Decathlon"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "A white hat is?",
                    "A philanthropic penetration tester",
                    "A malicious penetration tester",
                    "A neutral penetration tester",
                    "An invisible hacker",
                    "Something to wear when very hot"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is the abbreviation SUT short for?",
                    "system under test",
                    "solution utilization tracker",
                    "system utilization tracker",
                    "system under trial",
                    "Suspected Underwear thief"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is unobtrusive javascript?",
                    "javascript that's in a file rather than intruding into the html page",
                    "javascript that's in the html page rather than in a file",
                    "raw javascript that is not polluted with any js frameworks",
                    "javascript after it has been minified",
                    "javascript that doesn't contain any swear words"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is the abbreviation SOA short for?",
                    "service oriented architecture",
                    "soap oriented architecture",
                    "systems oriented architecture",
                    "solutions oriented architecture",
                    "save our aragutans"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is the acronym SOAP short for?",
                    "Simple Object Access Protocol",
                    "Service oriented architecture Protocol",
                    "Standard Object Accessor Pattern",
                    "Security Offensive Attack Principal",
                    "soap obscures all pongs"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is the big-data related CAP theorem short for?",
                    "Consistency Availability Partition Tolerance",
                    "Consistency Availability Partition",
                    "Consistent Atomic Platform",
                    "Clone Available Pieces",
                    "climates and primates"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "The data-related acronym ACID is short for?",
                    "Atomicity Consistency Isolation Durability",
                    "Artifically Cloned Integrated Data",
                    "Active Cloud Integrated Data",
                    "Atomic Consistent Independent Data",
                    "anti-climactic ignorance day"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is the acronym REST short for?",
                    "REpresentational State Transfer",
                    "Really Easy Server Transport",
                    "Registry Extraction for System Testing",
                    "REgular Silent Transfers",
                    "a mars a day helps you work REST and play"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What was an original name for Babel",
                    "6 to 5",
                    "9 to 5",
                    "Tower.JS",
                    "JS.Tower",
                    "Babe-L"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "In C#, what are verbatim strings?",
                    "Strings that start with the @ symbol in which the escape sequences are not processed",
                    "Strings that use the backslash character as an escape character",
                    "Strings that are formatted from strings and separately listed parametrized values",
                    "Strings that are formatted from strings and embedded parametrized values",
                    "Strings that contain the word 'verbatim'"),
            };

            return gatewayResponses;
        }
    }
}
