using Quiz.Questions.Entities;
using System.Collections.Generic;

namespace Quiz.Questions.Categories.Geek
{
    internal class QuestionsWebCampTrainingKit : IGetGeeks
    {
        public IEnumerable<GatewayResponse> GetGatewayResponses()
        {
            var gatewayResponses = new List<GatewayResponse>
            {
                Common.Get(Category.Geek, DifficultyLevel.Medium, "When was .NET first released?",
                    "2002", // IsCorrect = true),
                    "2000",
                    "2001",
                    "2003"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What fictional company did Nancy Davolio work for?",
                    "Northwind Traders", //// IsCorrect = true}
                    "Contoso Ltd.",
                    "Initech",
                    "Fabrikam, Inc."),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "The first / oldest domain name on the internet is:",
                    "Symbolics.com", // IsCorrect = true),
                    "Network.com",
                    "Alpha4.com",
                    "InterConnect.com"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "Which is not actually a Thing.js?",
                    "Horseradish.js", // IsCorrect = true),
                    "Mustache.js",
                    "Hammer.js",
                    "Uglify.js"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "In what year was the first Voice Over IP (VOIP) call made?",
                    "1973", // IsCorrect = true),
                    "1982",
                    "1991",
                    "1994"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "\"Chicago\" was codename for what Microsoft product?",
                    "Windows 95", // IsCorrect = true),
                    "Visual Basic",
                    "Microsoft Surface",
                    "Xbox"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "How many loop constructs are there in C#?",
                    "4", // IsCorrect = true),
                    "2",
                    "3",
                    "5"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What was the first CodePlex.com project?",
                    "IronPython", // IsCorrect = true),
                    "EntLib",
                    "Ajax Toolkit",
                    "JSON.Net"),
                Common.Get(Category.Geek, DifficultyLevel.Medium,
                    "Last name of the employee who wears Microsoft badge 00001",
                    "McDonald", // IsCorrect = true),
                    "Gates",
                    "Ballmer",
                    "Allen"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "When did Scott Hanselman join Microsoft?",
                    "2007", // IsCorrect = true),
                    "2000",
                    "2005",
                    "2009"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "How big is a nibble?",
                    "4 bits", // IsCorrect = true),
                    "8 bits",
                    "16 bits",
                    "2 bits"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "How many function calls did Windows 1.0 approximately have?",
                    "400", // IsCorrect = true}
                    "100",
                    "200",
                    "600"),
                Common.Get(Category.Geek, DifficultyLevel.Easy,
                    "What is the image name for the Windows Task Manager application?",
                    "taskmgr", // IsCorrect = true),
                    "tmanager",
                    "wtaskmgr",
                    "wintaskm"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "When was the internet opened to commercial use?",
                    "1991", //IsCorrect = true}
                    "1989",
                    "1992",
                    "1990"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "When was the Xbox unveiled?",
                    "2001", // IsCorrect = true),
                    "2000",
                    "2002",
                    "2003"),
                Common.Get(Category.Geek, DifficultyLevel.Medium,
                    "What is the value of an Object + Array in JavaScript?",
                    "0", // IsCorrect = true),
                    "Array",
                    "Object",
                    "Type Error"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Why was the IBM PCjr despised by users?",
                    "All the above", //IsCorrect = true}
                    "Chicklet keyboard",
                    "No Hard Disk",
                    "Not PC compatible"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What was the max memory supported by MS-DOS?",
                    "1M", // IsCorrect = true}
                    "256K",
                    "512K",
                    "640K"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "When was the first laser mouse released?",
                    "2004", // IsCorrect = true}
                    "2001",
                    "2002",
                    "2003"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What was Microsoft's first product?",
                    "Altair Basic", // IsCorrect = true),
                    "DOS",
                    "PC Basic",
                    "Windows"),
                Common.Get(Category.Geek, DifficultyLevel.Medium,
                    "What building does not exist on the Microsoft campus?",
                    "7", // IsCorrect = true),
                    "1",
                    "99",
                    "115"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Who wrote the first computer program?",
                    "Ada Lovelace", // IsCorrect = true),
                    "Charles Babbage",
                    "Herman Hollerith",
                    "Jakob Bernoulli"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Visual Basic was first released in what year?",
                    "1991", // IsCorrect = true),
                    "1990",
                    "1992",
                    "1993"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Which of the following is NOT a prime number?",
                    "697", // IsCorrect = true}
                    "257",
                    "379",
                    "571"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "Yukihiro Matsumoto conceived what programming language on February 24, 1993?",
                    "Ruby", // IsCorrect = true),
                    "Python",
                    "Perl",
                    "Boo"),
                Common.Get(Category.Geek, DifficultyLevel.Medium,
                    "Which release of the .NET Framework introduced support for dynamic languages?",
                    "4.0", // IsCorrect = true}
                    "1.1",
                    "2.0",
                    "3.5"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "What is the package manager for Node.js?",
                    "npm", // IsCorrect = true),
                    "yum",
                    "rpm",
                    "PEAR"),
                Common.Get(Category.Geek, DifficultyLevel.Easy, "In the acronym PaaS, what do the P stand for",
                    "Platform", // IsCorrect = true),
                    "Programming",
                    "Power",
                    "Pedestrian"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What is the speed of light in metres per second?",
                    "299,792,458", // IsCorrect = true),
                    "312,123,156",
                    "100,000,000",
                    "541,123,102"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "What was the original name of the C# programming language?",
                    "Cool", // IsCorrect = true),
                    "Boo",
                    "C+++",
                    "Anders"),
                Common.Get(Category.Geek, DifficultyLevel.Medium,
                    "Which of the following is an example of Boxing in C#?",
                    "object bar = 42;", // IsCorrect = true}
                    "int foo = 12;",
                    "System.Box(56);",
                    "int foo = (int)bar;"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "Which of the following was not an alternative name considered for XML?",
                    "SGML", // IsCorrect = true),
                    "MAGMA",
                    "SLIM",
                    "MGML"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "How many HTML tags are defined in the original description of the markup language?",
                    "18", // IsCorrect = true),
                    "1",
                    "11",
                    "25"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "Which of the following ECMA standards represents the standardization of JavaScript?",
                    "ECMA-262", // IsCorrect = true),
                    "ECMA-123",
                    "ECMA-301",
                    "ECMA-431"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "What was the first Web Browser called?",
                    "WorldWideWeb", // IsCorrect = true),
                    "Mosaic",
                    "Lynx",
                    "Gopher"),
                Common.Get(Category.Geek, DifficultyLevel.Easy,
                    "In version control systems, the process of bringing together two sets of changes is called what?",
                    "Merge", // IsCorrect = true),
                    "Branch",
                    "Commit",
                    "Share"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "In 1980, Microsoft released there first operating system. What was it called?",
                    "Xenix", // IsCorrect = true),
                    "MS-DOS",
                    "Windows",
                    "Altair OS"),
                Common.Get(Category.Geek, DifficultyLevel.Medium,
                    "Which ASCII code (in decimal) represents the character B?",
                    "66", // IsCorrect = true),
                    "22",
                    "97",
                    "112"),
                Common.Get(Category.Geek, DifficultyLevel.Hard, "Which are the first 6 decimal digits of Pi?",
                    "3.14159", // IsCorrect = true),
                    "3.14195",
                    "3.14132",
                    "3.14123"),
                Common.Get(Category.Geek, DifficultyLevel.Hard,
                    "Internet Protocol v4 provides approximately how many addresses?",
                    "4.3 billion", // IsCorrect = true),
                    "1.5 billion",
                    "55 billion",
                    "3.4 trillion"),
                Common.Get(Category.Geek, DifficultyLevel.Medium, "What is Layer 4 of the OSI Model?",
                    "Transport Layer", // IsCorrect = true),
                    "Network Layer",
                    "Session Layer",
                    "Presentation Layer"),
                Common.Get(Category.Geek, DifficultyLevel.Easy,
                    "Which of the following is NOT a value type in the .NET Framework Common Type System?",
                    "System.String", // IsCorrect = true),
                    "System.Integer",
                    "System.DateTime",
                    "System.Float")
            };

            return gatewayResponses;
        }
    }
}
