// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quiz.Ui.Music
{
    static class Vsix
    {
        public const string Id = "422e4080-3af8-48f7-870b-1800fa9fd60b";
        public const string Name = "Music Quiz";
        public const string Description = @"A multi-choice music quiz when you open Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.3";
        public const string Author = "Greg Trevellick";
        public const string Tags = "MusicQuiz, music, quiz, fun, trivia, trivial";
    }
}
