// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quiz.Ui
{
    static class Vsix
    {
        public const string Id = "ea0eead2-1392-4c13-bb81-6f6c5de8a936";
        public const string Name = "Geek Quiz";
        public const string Description = @"A multi-choice geek quiz when you open Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Greg Trevellick";
        public const string Tags = "GeekQuiz; geek; quiz; fun; trivia; trivial";
    }
}
