// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeekQuiz.Ui
{
    static class Vsix
    {
        public const string Id = "GeekQuiz.Ui.f13b6424-a884-4895-bd51-0cbdf2f7bbea";
        public const string Name = "GeekQuiz.Ui";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "";
    }
}
