// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeekQuiz.Ui
{
    static class Vsix
    {
        public const string Id = "f13b6424-a884-4895-bd51-0cbdf2f7bbea";
        public const string Name = "GeekQuiz";
        public const string Description = @"A multi-choice computer science quiz whenever you open a solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "GeekQuiz, geek, quiz, fun, trivia";
    }
}
